# Generated by Django 5.2.8 on 2025-11-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_seat_is_booked_alter_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='has_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='has_chargingport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='min_price',
            field=models.FloatField(default=450),
            preserve_default=False,
        ),
    ]
