# Generated by Django 5.2.8 on 2025-11-21 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_bus_has_ac_bus_has_chargingport_bus_has_wifi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bus.bus'),
        ),
    ]
